openapi: 3.0.3
info:
  title: Pet Service
  version: 1.0.0
tags:
  - name: Pet # Имя тега определит название класса: PetApi
paths:
  /pet/{petId}:
    get:
      tags:
        - Pet # Обязательно привязываем метод к тегу
      summary: Get pet by ID
      operationId: getPetById
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      type: object
      properties:
        id: { type: integer, format: int64 }
        name: { type: string }
        status: { type: string }